name = "workers"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "ProxyIP.US.CMLiussss.net"
UUID = "61e1283c-fc1e-4768-8c0a-5156e697b69a"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
